# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TimeTable.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TimeTable(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(829, 426)
        Form.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        Form.setStyleSheet("background-color: rgb(56, 58,89);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 120, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 220, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 320, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(430, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(430, 120, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(430, 220, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(430, 320, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.hour1ComboBox = QtWidgets.QComboBox(Form)
        self.hour1ComboBox.setGeometry(QtCore.QRect(180, 20, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hour1ComboBox.setFont(font)
        self.hour1ComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hour1ComboBox.setStyleSheet("color: rgb(255, 111, 253);\n"
"border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;")
        self.hour1ComboBox.setCurrentText("")
        self.hour1ComboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.hour1ComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.hour1ComboBox.setObjectName("hour1ComboBox")
        self.hour2ComboBox = QtWidgets.QComboBox(Form)
        self.hour2ComboBox.setGeometry(QtCore.QRect(180, 120, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hour2ComboBox.setFont(font)
        self.hour2ComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hour2ComboBox.setStyleSheet("color: rgb(255, 111, 253);\n"
"border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;")
        self.hour2ComboBox.setCurrentText("")
        self.hour2ComboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.hour2ComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.hour2ComboBox.setObjectName("hour2ComboBox")
        self.hour3ComboBox = QtWidgets.QComboBox(Form)
        self.hour3ComboBox.setGeometry(QtCore.QRect(180, 220, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hour3ComboBox.setFont(font)
        self.hour3ComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hour3ComboBox.setStyleSheet("color: rgb(255, 111, 253);\n"
"border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;")
        self.hour3ComboBox.setCurrentText("")
        self.hour3ComboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.hour3ComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.hour3ComboBox.setObjectName("hour3ComboBox")
        self.hour4ComboBox = QtWidgets.QComboBox(Form)
        self.hour4ComboBox.setGeometry(QtCore.QRect(180, 320, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hour4ComboBox.setFont(font)
        self.hour4ComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hour4ComboBox.setStyleSheet("color: rgb(255, 111, 253);\n"
"border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;")
        self.hour4ComboBox.setCurrentText("")
        self.hour4ComboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.hour4ComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.hour4ComboBox.setObjectName("hour4ComboBox")
        self.hour5ComboBox = QtWidgets.QComboBox(Form)
        self.hour5ComboBox.setGeometry(QtCore.QRect(580, 20, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hour5ComboBox.setFont(font)
        self.hour5ComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hour5ComboBox.setStyleSheet("color: rgb(255, 111, 253);\n"
"border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;")
        self.hour5ComboBox.setCurrentText("")
        self.hour5ComboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.hour5ComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.hour5ComboBox.setObjectName("hour5ComboBox")
        self.hour6ComboBox = QtWidgets.QComboBox(Form)
        self.hour6ComboBox.setGeometry(QtCore.QRect(580, 120, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hour6ComboBox.setFont(font)
        self.hour6ComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hour6ComboBox.setStyleSheet("color: rgb(255, 111, 253);\n"
"border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;")
        self.hour6ComboBox.setCurrentText("")
        self.hour6ComboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.hour6ComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.hour6ComboBox.setObjectName("hour6ComboBox")
        self.hour7ComboBox = QtWidgets.QComboBox(Form)
        self.hour7ComboBox.setGeometry(QtCore.QRect(580, 220, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hour7ComboBox.setFont(font)
        self.hour7ComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hour7ComboBox.setStyleSheet("color: rgb(255, 111, 253);\n"
"border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;")
        self.hour7ComboBox.setCurrentText("")
        self.hour7ComboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.hour7ComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.hour7ComboBox.setObjectName("hour7ComboBox")
        self.hour8ComboBox = QtWidgets.QComboBox(Form)
        self.hour8ComboBox.setGeometry(QtCore.QRect(580, 320, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hour8ComboBox.setFont(font)
        self.hour8ComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hour8ComboBox.setStyleSheet("color: rgb(255, 111, 253);\n"
"border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;")
        self.hour8ComboBox.setCurrentText("")
        self.hour8ComboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.hour8ComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.hour8ComboBox.setObjectName("hour8ComboBox")
        self.submitButton = QtWidgets.QPushButton(Form)
        self.submitButton.setGeometry(QtCore.QRect(360, 380, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.submitButton.setFont(font)
        self.submitButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"background-color: rgba(255,255,255,40)\n"
"\n"
"")
        self.submitButton.setObjectName("submitButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Hour 1"))
        self.label_2.setText(_translate("Form", "Hour 2"))
        self.label_3.setText(_translate("Form", "Hour 3"))
        self.label_4.setText(_translate("Form", "Hour 4"))
        self.label_5.setText(_translate("Form", "Hour 5"))
        self.label_6.setText(_translate("Form", "Hour 6"))
        self.label_7.setText(_translate("Form", "Hour 7"))
        self.label_8.setText(_translate("Form", "Hour 8"))
        self.submitButton.setText(_translate("Form", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_TimeTable()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
