# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'week.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import ui
class Ui_Week(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(387, 226)
        Form.setStyleSheet("background-color: rgb(56, 58,89);")
        Form.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 10, 381, 180))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.ThursdayButton = QtWidgets.QPushButton(self.frame)
        self.ThursdayButton.setGeometry(QtCore.QRect(20, 110, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ThursdayButton.setFont(font)
        self.ThursdayButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"background-color: rgba(255,255,255,40)\n"
"\n"
"")
        self.ThursdayButton.setObjectName("ThursdayButton")
        self.WednesdayButton = QtWidgets.QPushButton(self.frame)
        self.WednesdayButton.setGeometry(QtCore.QRect(260, 40, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.WednesdayButton.setFont(font)
        self.WednesdayButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"background-color: rgba(255,255,255,40)\n"
"\n"
"")
        self.WednesdayButton.setObjectName("WednesdayButton")
        self.TuesdayButton = QtWidgets.QPushButton(self.frame)
        self.TuesdayButton.setGeometry(QtCore.QRect(140, 40, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.TuesdayButton.setFont(font)
        self.TuesdayButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"background-color: rgba(255,255,255,40)\n"
"\n"
"")
        self.TuesdayButton.setObjectName("TuesdayButton")
        self.SaturdayButton = QtWidgets.QPushButton(self.frame)
        self.SaturdayButton.setGeometry(QtCore.QRect(260, 110, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SaturdayButton.setFont(font)
        self.SaturdayButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"background-color: rgba(255,255,255,40)\n"
"\n"
"")
        self.SaturdayButton.setObjectName("SaturdayButton")
        self.MondayButton = QtWidgets.QPushButton(self.frame)
        self.MondayButton.setGeometry(QtCore.QRect(20, 40, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.MondayButton.setFont(font)
        self.MondayButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"background-color: rgba(255,255,255,40)\n"
"\n"
"")
        self.MondayButton.setObjectName("MondayButton")
        self.FridayButton = QtWidgets.QPushButton(self.frame)
        self.FridayButton.setGeometry(QtCore.QRect(140, 110, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.FridayButton.setFont(font)
        self.FridayButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"background-color: rgba(255,255,255,40)\n"
"\n"
"")
        self.FridayButton.setObjectName("FridayButton")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(360, 0, 16, 16))
        self.pushButton.setStyleSheet("border-image: url(:/images/cancel.png);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(lambda:Form.close())
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ThursdayButton.setText(_translate("Form", "Thursday"))
        self.WednesdayButton.setText(_translate("Form", "Wednesday"))
        self.TuesdayButton.setText(_translate("Form", "Tuesday"))
        self.SaturdayButton.setText(_translate("Form", "Saturday"))
        self.MondayButton.setText(_translate("Form", "Monday"))
        self.FridayButton.setText(_translate("Form", "Friday"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Week()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
